use megalodon::entities::{Account, Status, StatusVisibility};

pub fn plain_account() -> Account {
    Account {
        id: Default::default(),
        username: Default::default(),
        acct: Default::default(),
        display_name: Default::default(),
        locked: Default::default(),
        discoverable: Default::default(),
        group: Default::default(),
        noindex: Default::default(),
        moved: Default::default(),
        suspended: Default::default(),
        limited: Default::default(),
        created_at: Default::default(),
        followers_count: Default::default(),
        following_count: Default::default(),
        statuses_count: Default::default(),
        note: Default::default(),
        url: Default::default(),
        avatar: Default::default(),
        avatar_static: Default::default(),
        header: Default::default(),
        header_static: Default::default(),
        emojis: Default::default(),
        fields: Default::default(),
        bot: Default::default(),
        source: Default::default(),
        role: Default::default(),
        mute_expires_at: Default::default(),
    }
}

pub fn plain_status() -> Status {
    Status {
        id: Default::default(),
        uri: Default::default(),
        url: Default::default(),
        account: plain_account(),
        in_reply_to_id: Default::default(),
        in_reply_to_account_id: Default::default(),
        reblog: Default::default(),
        content: Default::default(),
        plain_content: Default::default(),
        created_at: Default::default(),
        edited_at: Default::default(),
        emojis: Default::default(),
        replies_count: Default::default(),
        reblogs_count: Default::default(),
        favourites_count: Default::default(),
        reblogged: Default::default(),
        favourited: Default::default(),
        muted: Default::default(),
        sensitive: Default::default(),
        spoiler_text: Default::default(),
        visibility: StatusVisibility::Public,
        media_attachments: Default::default(),
        mentions: Default::default(),
        tags: Default::default(),
        card: Default::default(),
        poll: Default::default(),
        application: Default::default(),
        language: Default::default(),
        pinned: Default::default(),
        emoji_reactions: Default::default(),
        quote: Default::default(),
        bookmarked: Default::default(),
    }
}
